version: 0.2
phases:
  install:
    runtime-versions:
        nodejs: 10
  build:
    commands:
      - echo hello
# artifacts:
#   type: zip
#   files:
#     - template.yml
#     - outputtemplate.yml